const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const vm = require('node:vm');
const {start} = require('../server.cjs');
const {localStore} = require('../lib/database.cjs');

test('JSON database: complete authenticated lifecycle and durable storage', async t => {
  const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'bijoytower-test-'));
  const server = await start({port: 0, dataDir});
  t.after(async () => {await new Promise(resolve => server.close(resolve)); await fs.rm(dataDir, {recursive:true, force:true});});
  const base = 'http://127.0.0.1:' + server.address().port;
  let cookie = '';
  async function request(body, useCookie = true, extraHeaders = {}) {
    const response = await fetch(base + '/api/database', {method: body ? 'POST' : 'GET', headers: {'Content-Type':'application/json', ...(useCookie ? {cookie} : {}), ...extraHeaders}, body: body ? JSON.stringify(body) : undefined});
    if (response.headers.has('set-cookie')) cookie = response.headers.get('set-cookie').split(';')[0];
    return {status:response.status, body:await response.json()};
  }
  const initial = await request();
  assert.equal(initial.body.session, null);
  assert.equal(initial.body.state.flats.length, 0);
  assert.equal((await request({action:'save', revision:0, state:{flats:[],entries:[]}}, false)).status, 403);
  assert.equal((await request({action:'login',role:'admin',pin:'wrong'}, false)).status, 401);
  const access = await fs.readFile(path.join(dataDir, 'PRIVATE-ACCESS.txt'), 'utf8');
  const pin = access.match(/PIN: (\d+)/)[1];
  const login = await request({action:'login',role:'admin',pin});
  assert.equal(login.body.session.role, 'admin');
  const adminCookie = cookie;
  const flats = Array.from({length:27}, (_,i) => ({flatNo:'A-'+(i+1), ownerName:'মালিক '+i, mobile:'017'+String(i).padStart(8,'0')}));
  const entries = flats.map((f,i) => ({id:'entry-'+i,type:'income',category:'সার্ভিস চার্জ',amount:3000,month:'2026-09',flatNo:f.flatNo,note:''}));
  let saved = await request({action:'save',revision:0,state:{flats,entries}});
  assert.equal(saved.status, 200);
  assert.equal(saved.body.revision, 1);
  assert.equal((await request()).body.state.flats.length, 27);
  assert.equal((await request({action:'save',revision:0,state:{flats:[],entries:[]}})).status, 409);
  assert.equal((await request({action:'save',revision:1,state:{flats:[...flats,flats[0]],entries}})).status, 400);
  assert.equal((await request({action:'save',revision:1,state:{flats,entries}}, true, {origin:'https://evil.example'})).status, 403);
  assert.equal((await request({action:'save',revision:1,state:{flats,entries:[]}}, false)).status, 403);
  flats[0].ownerName = 'সম্পাদিত নাম'; entries[0].amount = 3500;
  saved = await request({action:'save',revision:1,state:{flats,entries}});
  assert.equal(saved.status, 200);
  const freshStore = await localStore(path.join(dataDir,'database.json')).read();
  assert.equal(freshStore.database.flats[0].ownerName, 'সম্পাদিত নাম');
  assert.equal(freshStore.database.entries[0].amount, 3500);
  assert.ok(await fs.stat(path.join(dataDir,'database.json.bak')));
  assert.notEqual(freshStore.database.auth.hash, pin);
  assert.equal((await fetch(base+'/data/database.json')).status, 404);
  assert.equal((await fetch(base+'/data/PRIVATE-ACCESS.txt')).status, 404);
  assert.equal((await fetch(base+'/lib/database.cjs')).status, 404);
  await request({action:'logout'});
  assert.equal((await request()).body.session, null);
  const resident = await request({action:'login',role:'resident',phone:flats[0].mobile});
  assert.equal(resident.body.session.role, 'resident');
  assert.equal(resident.body.state.flats.length, 1);
  assert.equal(resident.body.state.entries.length, 27);
  assert.equal((await request({action:'save',revision:2,state:{flats:[],entries:[]}})).status, 403);
  cookie = adminCookie;
  const concurrent = await Promise.all([request({action:'save',revision:2,state:{flats,entries:[]}}), request({action:'save',revision:2,state:{flats:[],entries}})]);
  assert.deepEqual(concurrent.map(r=>r.status).sort(), [200,409]);
  const html = await (await fetch(base)).text();
  new vm.Script(html.match(/<script type="module">([\s\S]*?)<\/script>/)[1]);
  assert.doesNotMatch(html, /localStorage|firebase|firestore/i);
  assert.match(html, /\/api\/database/);
});
