const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const os=require('node:os');
const {JSDOM}=require('jsdom');
const {start}=require('../server.cjs');
const {createDatabase,validate}=require('../lib/database.cjs');
const A=require('../web/accounting.js');
test('screens: cashier bills, partial collection, garage, expense, phone edit, backup and resident login',async t=>{
 const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'bijoytower-ui-'));
 const initial={...createDatabase('1234'),...validate({flats:[{flatNo:'1A',ownerName:'নমুনা মালিক',mobile:'01700000001',serviceRate:3000,garageRate:500},{flatNo:'1B',ownerName:'দ্বিতীয় মালিক',mobile:'',serviceRate:3000}],entries:[],settings:{openingMonth:'2026-01',openingBalance:200}})};
 await fs.writeFile(path.join(dataDir,'database.json'),JSON.stringify(initial));
 const server=await start({port:0,dataDir});
 const base='http://127.0.0.1:'+server.address().port;
 const html=await fs.readFile(path.join(__dirname,'../index.html'),'utf8');
 const dom=new JSDOM(html,{url:base,runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;let cookie='',lastBlob;const errors=[];
 t.after(async()=>{w.close();await new Promise(resolve=>server.close(resolve));await fs.rm(dataDir,{recursive:true,force:true});});
 w.fetch=async(url,options={})=>{const response=await fetch(new URL(url,base),{...options,headers:{...options.headers,cookie}});if(response.headers.has('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return response;};
 w.structuredClone=structuredClone;w.confirm=()=>true;w.Blob=Blob;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.URL.createObjectURL=blob=>{lastBlob=blob;return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};
 w.addEventListener('error',event=>errors.push(event.error));
 w.eval(await fs.readFile(path.join(__dirname,'../web/accounting.js'),'utf8'));
 w.eval(await fs.readFile(path.join(__dirname,'../web/app.js'),'utf8'));
 async function until(check){for(let i=0;i<250;i++){if(await check())return;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error('UI condition timed out. '+w.document.body.textContent.slice(-500));}
 const query=selector=>w.document.querySelector(selector);
 const click=selector=>{assert.ok(query(selector),selector);query(selector).click();};
 const fill=(name,value)=>{const input=query('[name="'+name+'"]');assert.ok(input,name);input.value=value;};
 const submit=id=>query(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const read=async()=>JSON.parse(await fs.readFile(path.join(dataDir,'database.json'),'utf8'));
 async function saved(revision){await until(async()=> (await read()).revision===revision);await until(()=>!query('#busy-layer'));}
 await until(()=>query('#login-form'));
 click('[data-action="login-mode"][data-mode="admin"]');fill('credential','1234');submit('#login-form');
 await until(()=>query('[data-tab="collection"]'));click('[data-tab="collection"]');click('[data-action="generate"]');await saved(1);
 assert.equal((await read()).invoices.length,3);assert.equal((await read()).entries.length,0);
 click('[data-action="generate"]');assert.equal((await read()).revision,1);
 click('[data-action="collect"][data-flat="1A"]');fill('amount','1500');submit('#edit-form');await saved(2);
 let data=await read();assert.equal(A.flatAccount(data,data.flats[0],'2026-01').due,2000);
 click('[data-tab="garage"]');click('[data-action="new-garage"]');fill('payer','Test renter');fill('amount','600');submit('#edit-form');await saved(3);
 click('[data-tab="expenses"]');click('[data-action="new-cost"]');fill('amount','500');fill('note','Test expense');submit('#edit-form');await saved(4);
 data=await read();assert.equal(A.summary(data,'2026-01').closing,1800);
 click('[data-tab="flats"]');click('[data-action="edit-flat"][data-flat="1B"]');fill('mobile','01700000002');submit('#edit-form');await saved(5);
 assert.equal((await read()).flats[1].mobile,'01700000002');
 click('[data-tab="review"]');click('[data-action="backup"]');const backup=JSON.parse(await lastBlob.text());assert.equal(backup.version,2);assert.equal(backup.data.invoices.length,3);assert.equal(backup.data.entries.length,3);assert.equal(backup.data.auth,undefined);
 click('[data-action="logout"]');await until(()=>query('#login-form'));click('[data-action="login-mode"][data-mode="resident"]');fill('credential','01700000001');submit('#login-form');
 await until(()=>query('[data-tab="collection"]'));assert.equal(query('[data-tab="flats"]'),null);assert.equal(query('[data-tab="review"]'),null);
 click('[data-tab="collection"]');assert.equal(query('[data-action="collect"]'),null);assert.equal(query('tbody').children.length,1);assert.ok(w.document.body.textContent.includes('2,000'));
 assert.deepEqual(errors,[]);
});
