'use strict';
const A=Accounting, root=document.getElementById('app'), dialog=document.getElementById('editor');
let state=null, session=null, revision=0, selectedMonth='', tab='overview', loginMode='resident', search='', categoryFilter='', busy=false, syncError='', toastTimer;
const h=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const taka=value=>'৳ '+Number(value||0).toLocaleString('en-US',{maximumFractionDigits:2});
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const monthLabel=value=>new Date(value+'-01T12:00:00').toLocaleDateString('bn-BD',{month:'long',year:'numeric'});
const admin=()=>session?.role==='admin';
const button=(action,label,extra='',cls='')=>`<button type="button" data-action="${action}" class="${cls}" ${extra}>${label}</button>`;
const rowActions=(kind,id)=>admin()?`<div class="actions">${button('edit-'+kind,'সম্পাদনা',`data-id="${h(id)}"`,'small')}${button('delete-'+kind,'মুছুন',`data-id="${h(id)}"`,'small danger')}</div>`:'';
const sourceNote=e=>e.sourceId?`<span class="source">উৎস: ${h(e.sourceId)}</span>`:'';
function toast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.className='show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='',5500);}
async function api(body){const response=await fetch('/api/database',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let result;try{result=await response.json();}catch{throw new Error('সার্ভারের সাথে সংযোগ হচ্ছে না। আবার চেষ্টা করুন।');}if(!response.ok){const error=new Error(result.error||'অনুরোধ সম্পন্ন হয়নি।');error.status=response.status;throw error;}return result;}
function accept(result){state=result.state;session=result.session;revision=result.revision;syncError='';if(session&&!selectedMonth)selectedMonth=A.months(state).at(-1)||today().slice(0,7);}
async function refresh(){try{accept(await api());render();}catch(error){syncError=error.message;if(!state)root.innerHTML=`<main class="loading"><p>${h(error.message)}</p>${button('retry','আবার চেষ্টা করুন','','primary')}</main>`;else{render();toast(error.message,true);}}}
function showBusy(value){busy=value;document.getElementById('busy-layer')?.remove();if(value){const el=document.createElement('div');el.id='busy-layer';el.className='busy';el.innerHTML='<span>সংরক্ষণ হচ্ছে…</span>';document.body.appendChild(el);}}
async function commit(next){if(busy)return false;showBusy(true);try{accept(await api({action:'save',revision,state:next}));dialog.close();render();toast('সংরক্ষণ হয়েছে।');return true;}catch(error){if(error.status===409||error.status===403){try{accept(await api());}catch{}render();}const err=document.getElementById('form-error');if(err)err.textContent=error.message;toast(error.message,true);return false;}finally{showBusy(false);}}
function login(){root.innerHTML=`<main class="login"><section class="login-box"><h1>বিজয় টাওয়ার</h1><p>২৭ ফ্ল্যাটের সার্ভিস চার্জ ও আয়–ব্যয়ের হিসাব</p><div class="login-switch">${button('login-mode','ফ্ল্যাট মালিক','data-mode="resident"',loginMode==='resident'?'active':'')}${button('login-mode','ক্যাশিয়ার','data-mode="admin"',loginMode==='admin'?'active':'')}</div><form id="login-form"><label>${loginMode==='admin'?'ক্যাশিয়ারের পিন':'রেজিস্টার্ড মোবাইল নম্বর'}<input name="credential" ${loginMode==='admin'?'type="password" autocomplete="current-password"':'type="tel" autocomplete="tel" pattern="01[0-9]{9}" maxlength="11"'} inputmode="numeric" placeholder="${loginMode==='admin'?'পিন লিখুন':'01XXXXXXXXX'}" required></label><p id="login-error" class="form-error"></p><button class="primary" type="submit" style="width:100%">প্রবেশ করুন</button></form><p class="hint">${loginMode==='admin'?'পিন দিয়ে বিল, আদায়, ব্যয় ও মালিকের তথ্য পরিচালনা করুন।':'ক্যাশিয়ার আপনার ফ্ল্যাটের নম্বর যুক্ত করার পর এখানে হিসাব দেখতে পারবেন।'}</p></section></main>`;
 document.getElementById('login-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,value=new FormData(form).get('credential');form.querySelector('button').disabled=true;try{accept(await api({action:'login',role:loginMode,...(loginMode==='admin'?{pin:value}:{phone:value})}));selectedMonth=A.months(state).at(-1)||today().slice(0,7);tab='overview';render();}catch(error){document.getElementById('login-error').textContent=error.message;form.querySelector('button').disabled=false;}};
}
function render(){if(!session){login();return;}const pages=[['overview','সারসংক্ষেপ'],['collection',admin()?'বিল ও আদায়':'আমার ফ্ল্যাট'],['garage','বাইরের গ্যারেজ'],['expenses','ব্যয়'],...(admin()?[['flats','মালিকদের তালিকা']]:[]),['reports','মাসিক প্রতিবেদন'],...(admin()?[['review','যাচাই ও ব্যাকআপ']]:[])];if(!pages.some(p=>p[0]===tab))tab='overview';const titles=Object.fromEntries(pages);
 root.innerHTML=`<header><div><h1>${h(state.settings.buildingName)}</h1><p>${admin()?'ক্যাশিয়ার প্যানেল':h(session.flat.flatNo)+' · '+h(session.flat.ownerName)}</p></div>${button('logout','বের হন')}</header><main class="shell"><div class="toolbar"><div class="month"><label for="period">হিসাবের মাস</label><input id="period" type="month" min="${h(state.settings.openingMonth)}" value="${h(selectedMonth)}"></div><div class="actions">${button('refresh','হালনাগাদ করুন')}${button('print','প্রিন্ট')}${button('csv','CSV ডাউনলোড')}</div></div><nav>${pages.map(([key,label])=>button('tab',label,`data-tab="${key}"`,tab===key?'active':'')).join('')}</nav><h2 class="print-heading">${h(state.settings.buildingName)} — ${h(monthLabel(selectedMonth))}</h2>${syncError?`<div class="notice error">${h(syncError)} — সংরক্ষণ নিশ্চিত না হলে আবার চেষ্টা করুন।</div>`:''}<section id="content">${({overview,collection,garage,expenses,flats:flatList,reports:reportView,review:reviewView}[tab])()}</section><div class="footer">${h(titles[tab])} · ${h(monthLabel(selectedMonth))} · হিসাবের মাস ও প্রাপ্তির তারিখ আলাদা রাখা হয়েছে। বিল তৈরি মানে টাকা আদায় নয়।</div></main>`;
 document.getElementById('period').onchange=event=>{if(event.target.value&&event.target.value>=state.settings.openingMonth){selectedMonth=event.target.value;search='';render();}};
 const field=root.querySelector('[data-search]');if(field)field.oninput=event=>{const pos=event.target.selectionStart;search=event.target.value;render();const input=root.querySelector('[data-search]');input.focus();input.setSelectionRange(pos,pos);};
 const filter=root.querySelector('[data-category-filter]');if(filter)filter.onchange=event=>{categoryFilter=event.target.value;render();};
 const restore=document.getElementById('restore-file');if(restore)restore.onchange=event=>restoreFile(event.target.files[0]);
}
function card(label,value,cls=''){return `<div class="card ${cls}"><p>${label}</p><strong class="${value<0?'negative':''}">${taka(value)}</strong></div>`;}
function overview(){const s=A.summary(state,selectedMonth), report=state.reports.find(r=>r.month===selectedMonth),due=A.totalDue(state,selectedMonth);const own=!admin()?A.flatAccount(state,state.flats.find(f=>f.flatNo===session.flat.flatNo),selectedMonth):null;return `<h2>${h(monthLabel(selectedMonth))}</h2><div class="cards">${card('আগের মাসের জের',s.opening)}${card('এই মাসে আয়',s.received,'good')}${card('এই মাসে ব্যয়',s.expense)}${card('অবশিষ্ট / ঘাটতি',s.closing)}${card(own?'আমার ফ্ল্যাটের বকেয়া':'মোট পাওনা',own?own.due:due)}</div>${report&&Object.values(A.reconciliation(state,report)).some(v=>v!==0)?'<div class="notice">ছবির হিসাবের সঙ্গে কিছু পার্থক্য আছে। মাসিক প্রতিবেদনে গণনা ও ছবির অঙ্ক পাশাপাশি দেখুন।</div>':''}<div class="grid2"><div class="panel"><h2>আয়ের খাত</h2>${breakdown(s.income)}</div><div class="panel"><h2>ব্যয়ের খাত</h2>${breakdown(s.costs)}</div></div><div class="panel"><h2>মাসের আদায়</h2><p class="hint">সার্ভিস চার্জ, ফ্ল্যাটের গ্যারেজ ভাড়া এবং বহিরাগত গ্যারেজ ভাড়া পৃথক। আগের জের এই মাসের আয় নয়।</p>${entryTable(s.income,'income',true)}</div>`;}
function breakdown(rows){const totals={};for(const e of rows)totals[e.category]=(totals[e.category]||0)+e.amount;return Object.entries(totals).map(([key,value])=>`<div class="category-row"><span>${h(key)}</span><strong>${taka(value)}</strong></div>`).join('')||'<p class="empty">এই মাসে কোনো এন্ট্রি নেই।</p>';}
function collection(){let list=admin()?state.flats:state.flats.filter(f=>f.flatNo===session.flat.flatNo);list=list.filter(f=>(f.flatNo+' '+f.ownerName).toLowerCase().includes(search.toLowerCase()));const report=state.reports.find(r=>r.month===selectedMonth);return `<div class="toolbar"><div><h2>বিল, আদায় ও বকেয়া</h2><p class="hint">বকেয়া = প্রারম্ভিক পাওনা + বিল − সংশ্লিষ্ট আদায়। ঋণাত্মক অঙ্ক অগ্রিম জমা।</p></div><div class="actions">${admin()?button('generate','মাসিক বিল তৈরি','','primary')+button('new-invoice','একটি বিল যোগ')+button('new-income','আদায় লিখুন'):''}</div></div><input class="search" data-search placeholder="ফ্ল্যাট বা মালিক খুঁজুন" value="${h(search)}"><div class="panel" style="margin-top:15px"><div class="table-wrap"><table><thead><tr><th>ফ্ল্যাট / মালিক</th><th class="number">এই মাসের বিল</th><th class="number">সার্ভিস আদায়</th><th class="number">গ্যারেজ আদায়</th><th class="number">পুরোনো বকেয়া</th><th class="number">মোট বকেয়া</th>${report?'<th class="number">ছবির বকেয়া</th>':''}<th>বিস্তারিত</th></tr></thead><tbody>${list.map(f=>{const a=A.flatAccount(state,f,selectedMonth),printed=report?.dues[f.flatNo]||0;return `<tr><td class="owner"><strong>${h(f.flatNo)}</strong><br>${h(f.ownerName)}</td><td class="number">${taka(a.billed)}</td><td class="number">${taka(a.servicePaid)}</td><td class="number">${taka(a.garagePaid)}</td><td class="number">${taka(a.previous)}</td><td class="number"><span class="badge ${a.due>0?'due':''}">${taka(a.due)}</span></td>${report?`<td class="number ${printed!==a.due?'negative':''}">${taka(printed)}</td>`:''}<td>${admin()?button('collect','আদায়',`data-flat="${h(f.flatNo)}"`,'small primary'):''}<details><summary>বিল ও রসিদ</summary>${a.bills.map(b=>`<p>${h(b.category)}: ${taka(b.amount)} ${admin()?button('edit-invoice','সম্পাদনা',`data-id="${h(b.id)}"`,'small'):''}</p>`).join('')}${a.receipts.map(e=>`<p>${h(e.date)} · ${h(e.category)} · ${taka(e.amount)} ${admin()?button('edit-entry','সম্পাদনা',`data-id="${h(e.id)}"`,'small'):''}</p>`).join('')||'<p>এই মাসে আদায় নেই।</p>'}</details></td></tr>`;}).join('')}</tbody></table></div></div>`;}
function entryTable(rows,kind,compact=false){const list=[...rows].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));return list.length?`<div class="table-wrap"><table><thead><tr><th>তারিখ</th><th>${kind==='garage'?'ভাড়াদাতার নাম':'খাত / নাম'}</th>${kind!=='garage'?'<th>ফ্ল্যাট</th>':''}<th class="number">পরিমাণ</th><th>বিবরণ / উৎস</th>${admin()?'<th>পরিচালনা</th>':''}</tr></thead><tbody>${list.map(e=>`<tr><td class="nowrap">${h(e.date)}${e.date.slice(0,7)!==e.month?'<br><span class="badge review">ভিন্ন মাসে প্রাপ্তি/প্রদান</span>':''}</td><td>${h(kind==='garage'?e.payer:e.category)}${kind!=='garage'&&e.payer?`<br><span class="muted">${h(e.payer)}</span>`:''}</td>${kind!=='garage'?`<td>${h(e.flatNo||'—')}</td>`:''}<td class="number">${taka(e.amount)}</td><td><details><summary>${e.note?h(e.note.slice(0,45))+(e.note.length>45?'…':''):'বিবরণ'}</summary><p>${h(e.note||'—')}</p>${sourceNote(e)}</details></td>${admin()?`<td>${rowActions('entry',e.id)}</td>`:''}</tr>`).join('')}</tbody><tfoot><tr><th colspan="${kind==='garage'?2:3}">মোট</th><th class="number">${taka(A.sum(list))}</th><th></th>${admin()?'<th></th>':''}</tr></tfoot></table></div>`:'<p class="empty">এই মাসে কোনো রেকর্ড নেই।</p>';}
function garage(){const rows=state.entries.filter(e=>e.type==='income'&&e.category===A.OUTSIDE&&e.month===selectedMonth&&(e.payer+' '+e.note).toLowerCase().includes(search.toLowerCase()));return `<div class="toolbar"><div><h2>বহিরাগত গ্যারেজ ভাড়া</h2><p class="hint">প্রতিটি আদায় একটি রসিদ। একই নামে একাধিক রসিদ আলাদাভাবে রাখা হয়েছে।</p></div>${admin()?button('new-garage','গ্যারেজ ভাড়া আদায়','','primary'):''}</div><input class="search" data-search placeholder="নাম খুঁজুন" value="${h(search)}"><div class="cards">${card('আদায়',A.sum(rows),'good')}<div class="card"><p>রসিদের সংখ্যা</p><strong>${rows.length}</strong></div></div><div class="panel">${entryTable(rows,'garage')}</div>`;}
function expenses(){const all=state.entries.filter(e=>e.type==='cost'&&e.month===selectedMonth);const categories=[...new Set(all.map(e=>e.category))];const rows=all.filter(e=>(!categoryFilter||e.category===categoryFilter)&&(e.note+' '+e.category).toLowerCase().includes(search.toLowerCase()));return `<div class="toolbar"><h2>ব্যয়ের খতিয়ান</h2>${admin()?button('new-cost','ব্যয় যোগ করুন','','primary'):''}</div><div class="toolbar"><input class="search" data-search placeholder="খাত বা বিবরণ খুঁজুন" value="${h(search)}"><select data-category-filter style="max-width:260px"><option value="">সব খাত</option>${categories.map(c=>`<option ${categoryFilter===c?'selected':''}>${h(c)}</option>`).join('')}</select></div><div class="panel">${entryTable(rows,'cost')}</div>`;}
function flatList(){const list=state.flats.filter(f=>(f.flatNo+' '+f.ownerName+' '+f.mobile).toLowerCase().includes(search.toLowerCase()));const missing=state.flats.filter(f=>!f.mobile).length;return `<div class="toolbar"><div><h2>ফ্ল্যাট মালিকদের তালিকা (${state.flats.length})</h2><p class="hint">মোবাইল নম্বর যুক্ত হলেই মালিক ফোন নম্বর দিয়ে প্রবেশ করতে পারবেন।</p></div>${button('new-flat','ফ্ল্যাট যোগ করুন','','primary')}</div>${missing?`<div class="notice">${missing}টি ফ্ল্যাটের মোবাইল নম্বর এখনো যোগ করা হয়নি। নাম ও ফ্ল্যাট নম্বর সংরক্ষিত আছে।</div>`:''}<input class="search" data-search placeholder="ফ্ল্যাট, নাম বা নম্বর খুঁজুন" value="${h(search)}"><div class="panel" style="margin-top:15px"><div class="table-wrap"><table><thead><tr><th>ফ্ল্যাট</th><th>মালিকের নাম</th><th>মোবাইল / লগইন</th><th class="number">মাসিক সার্ভিস</th><th class="number">মাসিক গ্যারেজ</th><th class="number">প্রারম্ভিক বকেয়া</th><th></th></tr></thead><tbody>${list.map(f=>`<tr><td><strong>${h(f.flatNo)}</strong>${!f.active?'<br><span class="badge">নিষ্ক্রিয়</span>':''}</td><td class="owner">${h(f.ownerName)}</td><td>${h(f.mobile)||'<span class="badge review">নম্বর প্রয়োজন</span>'}</td><td class="number">${taka(f.serviceRate)}</td><td class="number">${taka(f.garageRate)}</td><td class="number">${taka(f.openingDue)}</td><td>${button('edit-flat','সম্পাদনা',`data-flat="${h(f.flatNo)}"`,'small')}</td></tr>`).join('')}</tbody></table></div></div>`;}
function reportView(){const months=A.months(state);return `<div class="panel"><h2>মাসভিত্তিক আয়–ব্যয়</h2><p class="hint">জের আগের মাসের গণনাকৃত অবশিষ্ট থেকে আসে। ছবির অঙ্ক আলাদা তুলনার জন্য রাখা হয়েছে।</p><div class="table-wrap"><table><thead><tr><th>মাস</th><th class="number">প্রারম্ভিক জের</th><th class="number">আয়</th><th class="number">ব্যয়</th><th class="number">গণনাকৃত অবশিষ্ট</th><th class="number">ছবির অবশিষ্ট</th><th class="number">পার্থক্য</th></tr></thead><tbody>${months.map(month=>{const s=A.summary(state,month),r=state.reports.find(r=>r.month===month);return `<tr><td>${button('select-month',h(monthLabel(month)),`data-month="${month}"`,'small')}</td><td class="number">${taka(s.opening)}</td><td class="number">${taka(s.received)}</td><td class="number">${taka(s.expense)}</td><td class="number ${s.closing<0?'negative':''}">${taka(s.closing)}</td><td class="number">${r?taka(r.reportedClosing):'—'}</td><td class="number ${r&&s.closing!==r.reportedClosing?'negative':''}">${r?taka(s.closing-r.reportedClosing):'—'}</td></tr>`;}).join('')}</tbody></table></div></div><div class="panel"><h2>${h(monthLabel(selectedMonth))} — বিস্তারিত</h2>${entryTable(state.entries.filter(e=>e.month===selectedMonth),'all')}</div>`;}
function reviewView(){return `<div class="grid2"><div class="panel"><h2>ব্যাকআপ ও প্রারম্ভিক জের</h2><div class="actions">${button('backup','পূর্ণ JSON ব্যাকআপ','','primary')}${button('settings','প্রারম্ভিক জের সম্পাদনা')}</div><p class="hint">ব্যাকআপে নাম, নম্বর, বিল, আদায়, ব্যয় ও উৎসের তথ্য থাকে। পিন থাকে না।</p><label class="hint">ব্যাকআপ ফিরিয়ে আনুন<input type="file" id="restore-file" accept=".json,application/json"></label></div><div class="panel"><h2>পড়া ছবির হিসাব</h2><p>${state.sources.length}টি ছবি · ${state.reports.length} মাস · ${state.entries.length}টি লেনদেন · ${state.invoices.length}টি বিল</p><p class="hint">মূল ছবির সংখ্যা ও অঙ্ক সংরক্ষিত। অস্পষ্ট বা অসম্পূর্ণ তথ্য অনুমান করে আদায় হিসেবে যোগ করা হয়নি।</p></div></div><div class="panel"><h2>যাচাইয়ের বিষয়</h2>${state.reviewItems.map(r=>`<div class="review-item"><span class="badge ${r.status==='resolved'?'':'review'}">${r.status==='resolved'?'নোটসহ যাচাই করা':'যাচাই প্রয়োজন'}</span> ${r.month?h(monthLabel(r.month)):''}<p>${h(r.message)}</p>${r.resolution?`<p class="hint">ক্যাশিয়ারের নোট: ${h(r.resolution)}</p>`:''}${button('review-note','নোট / অবস্থা পরিবর্তন',`data-id="${h(r.id)}"`,'small')}</div>`).join('')}</div><div class="panel"><h2>উৎসের তালিকা</h2><div class="table-wrap"><table><thead><tr><th>মাস</th><th>ছবির নাম</th><th>তথ্যের ধরন</th></tr></thead><tbody>${state.sources.map(s=>`<tr><td>${h(s.month)}</td><td>${h(s.file)}</td><td>${h({'service':'ফ্ল্যাটের আদায় ও বকেয়া','outside-garage':'বাইরের গ্যারেজ','expenses':'ব্যয় ও জের','other-income':'অন্যান্য আয়'}[s.kind]||s.kind)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function field(label,name,value='',type='text',attrs='',full=false){return `<label class="${full?'full':''}">${label}<input name="${name}" type="${type}" value="${h(value)}" ${attrs}></label>`;}
function select(label,name,options,value,full=false){return `<label class="${full?'full':''}">${label}<select name="${name}">${options.map(o=>{const [key,label]=Array.isArray(o)?o:[o,o];return `<option value="${h(key)}" ${key===value?'selected':''}>${h(label)}</option>`;}).join('')}</select></label>`;}
function openForm(title,fields,onSubmit){if(!admin())return;dialog.innerHTML=`${button('close-dialog','×','','close')}<h2>${h(title)}</h2><form id="edit-form"><div class="fields">${fields}</div><p id="form-error" class="form-error"></p><div class="actions">${button('close-dialog','বাতিল')}<button type="submit" class="primary">সংরক্ষণ করুন</button></div></form>`;dialog.showModal();document.getElementById('edit-form').onsubmit=async event=>{event.preventDefault();try{await onSubmit(new FormData(event.currentTarget));}catch(error){document.getElementById('form-error').textContent=error.message;}};}
const clone=()=>structuredClone(state);
function entryForm(existing=null,defaults={}){const e=existing||{id:crypto.randomUUID(),type:'income',category:A.SERVICE,amount:3000,month:selectedMonth,date:today(),flatNo:'',payer:'',note:'',sourceId:'',...defaults};const categories=e.type==='income'?[A.SERVICE,A.GARAGE,A.OUTSIDE,'বকেয়া আদায়','অন্যান্য আয়']:['বিদ্যুৎ বিল','পানি বিল','নিরাপত্তা ও কেয়ারটেকার','ময়লা বিল','লিফট সার্ভিসিং','আদায় সম্মানী','সম্পাদক সম্মানী','গ্যাস বিল','মেরামত','পরিচ্ছন্নতা','ঈদ বোনাস','আইনি খরচ','আপ্যায়ন','যাতায়াত','অফিস খরচ',...state.entries.filter(v=>v.type==='cost').map(v=>v.category)];if(!categories.includes(e.category))categories.push(e.category);
 openForm(existing?'লেনদেন সম্পাদনা':e.type==='cost'?'ব্যয় যোগ করুন':'টাকা আদায় লিখুন',select('খাত','category',[...new Set(categories)],e.category)+field('পরিমাণ (৳)','amount',e.amount,'number','min="0.01" step="0.01" max="10000000000" required')+field('হিসাবের মাস','month',e.month,'month',`min="${state.settings.openingMonth}" required`)+field(e.type==='cost'?'প্রদানের তারিখ':'প্রাপ্তির তারিখ','date',e.date,'date','required')+select('ফ্ল্যাট (প্রযোজ্য হলে)','flatNo',[['','— বহিরাগত / সাধারণ —'],...state.flats.map(f=>[f.flatNo,f.flatNo+' — '+f.ownerName])],e.flatNo,true)+field('দাতা / প্রাপকের নাম','payer',e.payer,'text','maxlength="150"',true)+`<label class="full">বিবরণ<textarea name="note" maxlength="2000">${h(e.note)}</textarea></label>${sourceNote(e)}`,async form=>{const item={...e,category:form.get('category'),amount:Number(form.get('amount')),month:form.get('month'),date:form.get('date'),flatNo:form.get('flatNo'),payer:form.get('payer').trim(),note:form.get('note').trim()};if(A.receivableCategories.includes(item.category)&&!item.flatNo)throw new Error('সার্ভিস / গ্যারেজ / বকেয়া আদায়ের জন্য ফ্ল্যাট নির্বাচন করুন।');if(item.category===A.OUTSIDE&&!item.payer)throw new Error('বহিরাগত ভাড়াদাতার নাম লিখুন।');if(!item.payer&&item.flatNo)item.payer=state.flats.find(f=>f.flatNo===item.flatNo)?.ownerName||'';const next=clone(),index=next.entries.findIndex(v=>v.id===item.id);if(index<0)next.entries.push(item);else next.entries[index]=item;await commit(next);});}
function flatForm(no){const f=state.flats.find(f=>f.flatNo===no)||{flatNo:'',ownerName:'',mobile:'',serviceRate:3000,garageRate:0,openingDue:0,active:true};openForm(no?'মালিকের তথ্য সম্পাদনা':'ফ্ল্যাট যোগ করুন',field('ফ্ল্যাট নং','flatNo',f.flatNo,'text',`required maxlength="30" ${no?'readonly':''}`)+field('মালিকের নাম','ownerName',f.ownerName,'text','required maxlength="150"')+field('মোবাইল নম্বর (না থাকলে ফাঁকা)','mobile',f.mobile,'tel','pattern="01[0-9]{9}" maxlength="11"',true)+field('মাসিক সার্ভিস চার্জ','serviceRate',f.serviceRate,'number','min="0" step="0.01" required')+field('মাসিক গ্যারেজ ভাড়া','garageRate',f.garageRate,'number','min="0" step="0.01" required')+field('হিসাবের শুরুর বকেয়া / অগ্রিম','openingDue',f.openingDue,'number','step="0.01" required',true)+`<label class="checkbox full"><input type="checkbox" name="active" ${f.active?'checked':''}> এই ফ্ল্যাটের মাসিক বিল তৈরি হবে</label><p class="hint full">রেট পরিবর্তন করলে আগের বিল বদলাবে না। পুরোনো বকেয়া যাচাই ছাড়া পরিবর্তন করবেন না।</p>`,async form=>{const item={flatNo:form.get('flatNo').trim(),ownerName:form.get('ownerName').trim(),mobile:form.get('mobile').trim(),serviceRate:Number(form.get('serviceRate')),garageRate:Number(form.get('garageRate')),openingDue:Number(form.get('openingDue')),active:form.has('active')};const next=clone();if(no)next.flats[next.flats.findIndex(f=>f.flatNo===no)]=item;else next.flats.push(item);next.flats.sort((a,b)=>a.flatNo.localeCompare(b.flatNo,'en',{numeric:true}));await commit(next);});}
function invoiceForm(existing=null){const b=existing||{id:crypto.randomUUID(),month:selectedMonth,flatNo:state.flats[0]?.flatNo||'',category:A.SERVICE,amount:3000,note:'',sourceId:''};openForm(existing?'বিল সম্পাদনা':'বিল যোগ করুন',select('ফ্ল্যাট','flatNo',state.flats.map(f=>[f.flatNo,f.flatNo+' — '+f.ownerName]),b.flatNo,true)+select('খাত','category',[A.SERVICE,A.GARAGE],b.category)+field('বিলের পরিমাণ','amount',b.amount,'number','min="0.01" step="0.01" required')+field('হিসাবের মাস','month',b.month,'month',`min="${state.settings.openingMonth}" required`)+field('বিবরণ','note',b.note,'text','maxlength="2000"')+`<p class="hint full">বিল তৈরি / পরিবর্তন করলে টাকা আদায় হবে না।</p>${existing?button('delete-invoice','এই বিল মুছুন',`data-id="${h(b.id)}"`,'danger'):''}`,async form=>{const item={...b,flatNo:form.get('flatNo'),category:form.get('category'),amount:Number(form.get('amount')),month:form.get('month'),note:form.get('note')};const next=clone(),index=next.invoices.findIndex(v=>v.id===b.id);if(index<0)next.invoices.push(item);else next.invoices[index]=item;await commit(next);});}
function settingsForm(){openForm('প্রারম্ভিক হিসাব',field('ভবনের নাম','buildingName',state.settings.buildingName,'text','required',true)+field('হিসাবের শুরুর মাস','openingMonth',state.settings.openingMonth,'month','required')+field('প্রারম্ভিক নগদ জের (ঘাটতি হলে ঋণাত্মক)','openingBalance',state.settings.openingBalance,'number','step="0.01" required'),async form=>{const next=clone();next.settings={buildingName:form.get('buildingName'),openingMonth:form.get('openingMonth'),openingBalance:Number(form.get('openingBalance'))};await commit(next);});}
function reviewForm(id){const item=state.reviewItems.find(r=>r.id===id);openForm('যাচাইয়ের নোট',`<p class="hint full">${h(item.message)}</p><label class="full">নোট / সমর্থক তথ্য<textarea name="resolution" required maxlength="2000">${h(item.resolution)}</textarea></label>`+select('অবস্থা','status',[['open','যাচাই বাকি'],['resolved','নোটসহ যাচাই করা']],item.status),async form=>{const next=clone(),r=next.reviewItems.find(r=>r.id===id);r.resolution=form.get('resolution').trim();r.status=form.get('status');await commit(next);});}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function restoreFile(file){if(!file)return;try{if(file.size>3*1024*1024)throw new Error('৩ মেগাবাইটের বেশি ফাইল নেওয়া যাবে না।');const parsed=JSON.parse(await file.text());if(parsed.app!=='bijoytower'||parsed.version!==2||parsed.data?.schemaVersion!==2)throw new Error('এই সিস্টেমের পূর্ণ JSON ব্যাকআপ নির্বাচন করুন।');if(confirm('বর্তমান সব বিল ও হিসাব এই ব্যাকআপ দিয়ে প্রতিস্থাপন করবেন? আগে বর্তমান ব্যাকআপ ডাউনলোড করে রাখুন।'))await commit(parsed.data);}catch(error){toast(error.message,true);}}
function csv(){let rows;if(tab==='flats')rows=[['ফ্ল্যাট','মালিক','মোবাইল','সার্ভিস রেট','গ্যারেজ রেট','প্রারম্ভিক বকেয়া'],...state.flats.map(f=>[f.flatNo,f.ownerName,f.mobile,f.serviceRate,f.garageRate,f.openingDue])];else if(tab==='collection')rows=[['মাস','ফ্ল্যাট','মালিক','বিল','আদায়','মোট বকেয়া'],...state.flats.filter(f=>admin()||f.flatNo===session.flat.flatNo).map(f=>{const a=A.flatAccount(state,f,selectedMonth);return [selectedMonth,f.flatNo,f.ownerName,a.billed,a.paid,a.due];})];else rows=[['হিসাবের মাস','তারিখ','ধরন','খাত','ফ্ল্যাট','দাতা/প্রাপক','পরিমাণ','বিবরণ','উৎস'],...state.entries.filter(e=>e.month===selectedMonth&&(tab!=='garage'||e.category===A.OUTSIDE)&&(tab!=='expenses'||e.type==='cost')).map(e=>[e.month,e.date,e.type==='income'?'আয়':'ব্যয়',e.category,e.flatNo,e.payer,e.amount,e.note,e.sourceId])];const quote=value=>{let s=String(value??'');if(typeof value==='string'&&/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};download('\uFEFF'+rows.map(row=>row.map(quote).join(',')).join('\r\n'),'bijoytower-'+tab+'-'+selectedMonth+'.csv','text/csv;charset=utf-8');}
async function action(event){const el=event.target.closest('[data-action]');if(!el||busy)return;const {action,id,flat}=el.dataset;try{if(action==='login-mode'){loginMode=el.dataset.mode;login();return;}if(action==='retry'||action==='refresh'){await refresh();return;}if(action==='close-dialog'){dialog.close();return;}if(action==='logout'){accept(await api({action:'logout'}));selectedMonth='';render();return;}if(!session)return;if(action==='tab'){tab=el.dataset.tab;search='';categoryFilter='';render();return;}if(action==='select-month'){selectedMonth=el.dataset.month;tab='overview';render();return;}if(action==='print'){window.print();return;}if(action==='csv'){csv();return;}if(!admin())return;
 if(action==='new-flat'||action==='edit-flat'){flatForm(flat);return;}if(action==='new-income'){entryForm();return;}if(action==='collect'){entryForm(null,{flatNo:flat,payer:state.flats.find(f=>f.flatNo===flat).ownerName});return;}if(action==='new-garage'){entryForm(null,{category:A.OUTSIDE,amount:600});return;}if(action==='new-cost'){entryForm(null,{type:'cost',category:'বিদ্যুৎ বিল',amount:''});return;}if(action==='edit-entry'){entryForm(state.entries.find(e=>e.id===id));return;}if(action==='new-invoice'||action==='edit-invoice'){invoiceForm(state.invoices.find(e=>e.id===id));return;}
 if(action==='generate'){const bills=A.generateBills(state,selectedMonth);if(!bills.length){toast('এই মাসের সব বিল তৈরি করা আছে।');return;}if(confirm(monthLabel(selectedMonth)+' — '+bills.length+'টি বিল, মোট '+taka(A.sum(bills))+' তৈরি করবেন? এতে টাকা আদায় হবে না।')){const next=clone();next.invoices.push(...bills);await commit(next);}return;}
 if(action==='delete-entry'||action==='delete-invoice'){if(confirm('এই '+(action==='delete-entry'?'লেনদেন':'বিল')+' মুছে ফেলবেন? সংশ্লিষ্ট হিসাব পরিবর্তিত হবে।')){const next=clone(),key=action==='delete-entry'?'entries':'invoices';next[key]=next[key].filter(e=>e.id!==id);await commit(next);}return;}
 if(action==='backup'){download(JSON.stringify({app:'bijoytower',version:2,exportedAt:new Date().toISOString(),data:state},null,2),'bijoytower-backup-'+today()+'.json','application/json');return;}if(action==='settings'){settingsForm();return;}if(action==='review-note'){reviewForm(id);return;}
 }catch(error){toast(error.message,true);}}
root.addEventListener('click',action);dialog.addEventListener('click',action);
setInterval(async()=>{if(!session||busy||dialog.open||document.hidden)return;try{const result=await api();if(busy||dialog.open||result.revision<revision)return;syncError='';if(result.revision!==revision||!result.session){accept(result);render();}}catch(error){if(!syncError){syncError=error.message;render();}}},30000);
refresh();
