'use strict';
(function(root){
 const KEY='bijoytower-language';
 const en={
  'বিজয় টাওয়ার':'Bijoy Tower','২৭ ফ্ল্যাটের সার্ভিস চার্জ ও আয়–ব্যয়ের হিসাব':'Service charge, income and expense accounts for 27 flats',
  'ফ্ল্যাট মালিক':'Flat Owner','ক্যাশিয়ার':'Cashier','ক্যাশিয়ারের পিন':'Cashier PIN','রেজিস্টার্ড মোবাইল নম্বর':'Registered phone number','পিন লিখুন':'Enter PIN','প্রবেশ করুন':'Log in',
  'পিন দিয়ে বিল, আদায়, ব্যয় ও মালিকের তথ্য পরিচালনা করুন।':'Use the PIN to manage bills, collections, expenses and owner details.','ক্যাশিয়ার আপনার ফ্ল্যাটের নম্বর যুক্ত করার পর এখানে হিসাব দেখতে পারবেন।':'You can view your account here after the cashier adds your phone number.',
  'সারসংক্ষেপ':'Overview','বিল ও আদায়':'Payments','আমার ফ্ল্যাট':'My Payments','বাইরের গ্যারেজ':'Outside Garage','ব্যয়':'Expenses','মালিকদের তালিকা':'Owners','মাসিক প্রতিবেদন':'Reports','যাচাই ও ব্যাকআপ':'Data & Backup','ক্যাশিয়ার প্যানেল':'Cashier','বের হন':'Log out',
  'হিসাবের মাস':'Month','হালনাগাদ করুন':'Refresh','প্রিন্ট':'Print','CSV ডাউনলোড':'Download CSV','বাংলা':'বাংলা','English':'English',
  'সংরক্ষণ নিশ্চিত না হলে আবার চেষ্টা করুন।':'Try again if the save was not confirmed.','হিসাবের মাস ও প্রাপ্তির তারিখ আলাদা রাখা হয়েছে। বিল তৈরি মানে টাকা আদায় নয়।':'The account month and payment date are recorded separately. Creating a bill does not record a payment.',
  'আগের মাসের জের':'Previous Balance','এই মাসে আয়':'Monthly Income','এই মাসে ব্যয়':'Monthly Expense','অবশিষ্ট / ঘাটতি':'Current Balance','আমার ফ্ল্যাটের বকেয়া':'Due Amount','মোট পাওনা':'Total Due','এই মাসে আদায়':'Amount Paid',
  'ছবির হিসাবের সঙ্গে কিছু পার্থক্য আছে। মাসিক প্রতিবেদনে গণনা ও ছবির অঙ্ক পাশাপাশি দেখুন।':'Some calculated amounts differ from the source images. Compare them in Monthly Reports.',
  'আয়ের খাত':'Income Categories','ব্যয়ের খাত':'Expense Categories','মাসের আদায়':'Monthly Collections','সার্ভিস চার্জ, ফ্ল্যাটের গ্যারেজ ভাড়া এবং বহিরাগত গ্যারেজ ভাড়া পৃথক। আগের জের এই মাসের আয় নয়।':'Service charge, flat garage rent and outside garage rent are separate. The opening balance is not this month’s income.',
  'এই মাসে কোনো এন্ট্রি নেই।':'No entries this month.','এই মাসে কোনো রেকর্ড নেই।':'No records this month.','এই মাসে আদায় নেই।':'No collections this month.',
  'বিল, আদায় ও বকেয়া':'Bills, Collections & Dues','বকেয়া = প্রারম্ভিক পাওনা + বিল − সংশ্লিষ্ট আদায়। ঋণাত্মক অঙ্ক অগ্রিম জমা।':'Due = opening due + bills − related collections. A negative amount is an advance.',
  'মাসিক বিল তৈরি':'Create Monthly Bills','একটি বিল যোগ':'Add Bill','আদায় লিখুন':'New Payment','ফ্ল্যাট বা মালিক খুঁজুন':'Search Flat or Owner','ফ্ল্যাট / মালিক':'Flat / Owner','এই মাসের বিল':'This Month','সার্ভিস আদায়':'Service Paid','গ্যারেজ আদায়':'Garage Paid','পুরোনো বকেয়া':'Previous Due','মোট বকেয়া':'Total Due','ছবির বকেয়া':'Source Due','বিস্তারিত':'View Details','বিল ও রসিদ':'Bills & Receipts',
  'তারিখ':'Date','ভাড়াদাতার নাম':'Renter Name','খাত / নাম':'Category / Name','ফ্ল্যাট':'Flat','পরিমাণ':'Amount','বিবরণ / উৎস':'Description / Source','পরিচালনা':'Actions','ভিন্ন মাসে প্রাপ্তি/প্রদান':'Received/paid in another month','বিবরণ':'Description','মোট':'Total','উৎস':'Source',
  'বহিরাগত গ্যারেজ ভাড়া':'Outside Garage Rent','গ্যারেজ ভাড়া (বহিরাগত)':'Outside Garage Rent','গ্যারেজ ভাড়া (ফ্ল্যাট মালিক)':'Flat Garage Charge','প্রতিটি আদায় একটি রসিদ। একই নামে একাধিক রসিদ আলাদাভাবে রাখা হয়েছে।':'Each payment is kept separately.','গ্যারেজ ভাড়া আদায়':'Add Garage Payment','নাম খুঁজুন':'Search Name','আদায়':'Paid','রসিদের সংখ্যা':'Payments',
  'ব্যয়ের খতিয়ান':'Expenses','ব্যয় যোগ করুন':'Add Expense','খাত বা বিবরণ খুঁজুন':'Search expenses','সব খাত':'All Types',
  'মোবাইল নম্বর যুক্ত হলেই মালিক ফোন নম্বর দিয়ে প্রবেশ করতে পারবেন।':'An owner can log in after a phone number is added.','ফ্ল্যাট যোগ করুন':'Add Flat','নাম বা নম্বর খুঁজুন':'Search name or number','মালিকের নাম':'Owner Name','মোবাইল / লগইন':'Phone / Login','মাসিক সার্ভিস':'Monthly Service','মাসিক গ্যারেজ':'Monthly Garage','প্রারম্ভিক বকেয়া':'Opening Due','নিষ্ক্রিয়':'Inactive','নম্বর প্রয়োজন':'Phone Required',
  'মাসভিত্তিক আয়–ব্যয়':'Monthly Income & Expenses','জের আগের মাসের গণনাকৃত অবশিষ্ট থেকে আসে। ছবির অঙ্ক আলাদা তুলনার জন্য রাখা হয়েছে।':'The opening balance comes from the previous calculated balance. Source-image figures are kept for comparison.','মাস':'Month','প্রারম্ভিক জের':'Opening Balance','আয়':'Income','গণনাকৃত অবশিষ্ট':'Calculated Balance','ছবির অবশিষ্ট':'Source Balance','পার্থক্য':'Difference',
  'ব্যাকআপ ও প্রারম্ভিক জের':'Backup & Opening Balance','পূর্ণ JSON ব্যাকআপ':'Full JSON Backup','প্রারম্ভিক জের সম্পাদনা':'Edit Opening Balance','ব্যাকআপে নাম, নম্বর, বিল, আদায়, ব্যয় ও উৎসের তথ্য থাকে। পিন থাকে না।':'The backup contains names, phone numbers, bills, collections, expenses and source details. It does not contain the PIN.','ব্যাকআপ ফিরিয়ে আনুন':'Restore Backup','পড়া ছবির হিসাব':'Imported Source Records','মূল ছবির সংখ্যা ও অঙ্ক সংরক্ষিত। অস্পষ্ট বা অসম্পূর্ণ তথ্য অনুমান করে আদায় হিসেবে যোগ করা হয়নি।':'Source image counts and amounts are preserved. Unclear or incomplete items were not guessed as collections.','যাচাইয়ের বিষয়':'Items to Review','নোটসহ যাচাই করা':'Reviewed with Note','যাচাই প্রয়োজন':'Review Required','ক্যাশিয়ারের নোট':'Cashier Note','নোট / অবস্থা পরিবর্তন':'Edit Note / Status','উৎসের তালিকা':'Source List','ছবির নাম':'Image Name','তথ্যের ধরন':'Record Type','ফ্ল্যাটের আদায় ও বকেয়া':'Flat Collections & Dues','ব্যয় ও জের':'Expenses & Balances','অন্যান্য আয়':'Other Income',
  'সম্পাদনা':'Edit','মুছুন':'Delete','বাতিল':'Cancel','সংরক্ষণ করুন':'Save','সংরক্ষণ হচ্ছে…':'Saving…','সংরক্ষণ হয়েছে।':'Saved.','আবার চেষ্টা করুন':'Try Again','সার্ভারের সাথে সংযোগ হচ্ছে না। আবার চেষ্টা করুন।':'Cannot connect to the server. Please try again.','অনুরোধ সম্পন্ন হয়নি।':'The request could not be completed.',
  'সার্ভিস চার্জ':'Service Charge','বকেয়া আদায়':'Due Payment','বিদ্যুৎ বিল':'Electricity Bill','পানি বিল':'Water Bill','নিরাপত্তা ও কেয়ারটেকার':'Security & Caretaker','ময়লা বিল':'Waste Bill','লিফট সার্ভিসিং':'Lift Service','আদায় সম্মানী':'Collection Fee','সম্পাদক সম্মানী':'Secretary Fee','গ্যাস বিল':'Gas Bill','মেরামত':'Repair','পরিচ্ছন্নতা':'Cleaning','ঈদ বোনাস':'Eid Bonus','আইনি খরচ':'Legal Cost','আপ্যায়ন':'Refreshments','যাতায়াত':'Transport','অফিস খরচ':'Office Cost','ফ্ল্যাট গ্যারেজ ভাড়া':'Flat Garage Rent','পানি ট্যাংক পরিষ্কার':'Water Tank Cleaning','পানি সংক্রান্ত খরচ':'Water Work','বৈদ্যুতিক মালামাল':'Electrical Items','বিদ্যুৎ লাইন মেরামত':'Electrical Line Repair','বৈদ্যুতিক মেরামত':'Electrical Repair','পানির লাইন মেরামত':'Water Line Repair','সিসিটিভি':'CCTV','ধর্মীয় অনুষ্ঠান':'Religious Event','যাতায়াত ও আপ্যায়ন':'Transport & Refreshments','অগ্রিম':'Advance Balance','পূর্ণ':'Full','ব্যাকআপ':'Backup','বিল':'Bill','নম্বর':'Phone',
  'লেনদেন সম্পাদনা':'Edit Transaction','টাকা আদায় লিখুন':'Record Payment','খাত':'Category','পরিমাণ (৳)':'Amount (৳)','প্রদানের তারিখ':'Payment Date','প্রাপ্তির তারিখ':'Receipt Date','ফ্ল্যাট (প্রযোজ্য হলে)':'Flat (if applicable)','বহিরাগত / সাধারণ':'Outside / General','দাতা / প্রাপকের নাম':'Payer / Recipient Name','সার্ভিস / গ্যারেজ / বকেয়া আদায়ের জন্য ফ্ল্যাট নির্বাচন করুন।':'Select a flat for service, garage or due collections.','বহিরাগত ভাড়াদাতার নাম লিখুন।':'Enter the outside renter’s name.',
  'মালিকের তথ্য সম্পাদনা':'Edit Owner Details','ফ্ল্যাট নং':'Flat No.','মোবাইল নম্বর (না থাকলে ফাঁকা)':'Phone Number (leave blank if unavailable)','মাসিক সার্ভিস চার্জ':'Monthly Service Charge','মাসিক গ্যারেজ ভাড়া':'Monthly Garage Rent','হিসাবের শুরুর বকেয়া / অগ্রিম':'Opening Due / Advance','এই ফ্ল্যাটের মাসিক বিল তৈরি হবে':'Generate monthly bills for this flat','রেট পরিবর্তন করলে আগের বিল বদলাবে না। পুরোনো বকেয়া যাচাই ছাড়া পরিবর্তন করবেন না।':'Rate changes do not alter past bills. Do not change opening dues without verification.',
  'বিল সম্পাদনা':'Edit Bill','বিল যোগ করুন':'Add Bill','বিলের পরিমাণ':'Bill Amount','বিল তৈরি / পরিবর্তন করলে টাকা আদায় হবে না।':'Creating or changing a bill does not record a payment.','এই বিল মুছুন':'Delete This Bill','প্রারম্ভিক হিসাব':'Opening Account','ভবনের নাম':'Building Name','হিসাবের শুরুর মাস':'First Account Month','প্রারম্ভিক নগদ জের (ঘাটতি হলে ঋণাত্মক)':'Opening Cash Balance (negative for deficit)','যাচাইয়ের নোট':'Review Note','নোট / সমর্থক তথ্য':'Note / Supporting Information','অবস্থা':'Status','যাচাই বাকি':'Pending Review',
  '৩ মেগাবাইটের বেশি ফাইল নেওয়া যাবে না।':'Files larger than 3 MB are not accepted.','এই সিস্টেমের পূর্ণ JSON ব্যাকআপ নির্বাচন করুন।':'Select a full JSON backup from this system.','বর্তমান সব বিল ও হিসাব এই ব্যাকআপ দিয়ে প্রতিস্থাপন করবেন? আগে বর্তমান ব্যাকআপ ডাউনলোড করে রাখুন।':'Replace all current bills and accounts with this backup? Download the current backup first.','মালিক':'Owner','মোবাইল':'Phone','সার্ভিস রেট':'Service Rate','গ্যারেজ রেট':'Garage Rate','ধরন':'Type','দাতা/প্রাপক':'Payer/Recipient',
  'এই মাসের সব বিল তৈরি করা আছে।':'All bills for this month already exist.','তৈরি করবেন? এতে টাকা আদায় হবে না।':'Generate them? This will not record any payment.','লেনদেন':'transaction','মুছে ফেলবেন? সংশ্লিষ্ট হিসাব পরিবর্তিত হবে।':'Delete it? The related accounts will change.',
  'অনেকবার চেষ্টা হয়েছে। এক মিনিট পরে আবার চেষ্টা করুন।':'Too many attempts. Try again in one minute.','পিন সঠিক নয়।':'The PIN is incorrect.','এই মোবাইল নম্বরের কোনো ফ্ল্যাট পাওয়া যায়নি।':'No flat was found for this phone number.','ক্যাশিয়ার হিসেবে প্রবেশ করুন।':'Log in as cashier.','সিস্টেম আপডেট হয়েছে। পেজ রিফ্রেশ করুন।':'The system was updated. Refresh the page.','অন্য কেউ হিসাব পরিবর্তন করেছেন। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।':'Someone else changed the accounts. Refresh the page and try again.','ডাটাবেসে সংযোগ হয়নি। কিছুক্ষণ পরে আবার চেষ্টা করুন।':'Could not connect to the database. Try again shortly.',
  'সঠিক তথ্য লিখুন।':'Please check the information.','টাকার পরিমাণ সঠিক নয়।':'Please enter the amount.','হিসাবের মাস সঠিক নয়।':'Please choose a valid month.','তারিখ সঠিক নয়।':'Please choose a valid date.','তালিকা সঠিক নয়।':'This list is not valid.','একই তথ্য একাধিকবার আছে: ':'Duplicate: ','ডাটাবেস তথ্য নেই।':'Data is missing.','ফ্ল্যাটের তথ্য নেই।':'Flat information is missing.','মোবাইল নম্বর ০১ দিয়ে শুরু ১১ অঙ্কের হতে হবে।':'The phone number must contain 11 digits and start with 01.','মোবাইল নম্বর সঠিক নয়।':'Please enter a valid phone number.','বাংলাদেশের মোবাইল নম্বর ১১ অঙ্কের হতে হবে।':'A Bangladesh phone number must have 11 digits.','পরিশোধের শেষ তারিখ ১ থেকে ২৮ হতে হবে।':'The due day must be from 1 to 28.','লেনদেনের ধরন সঠিক নয়।':'Please choose a valid type.','টাকার পরিমাণ শূন্যের বেশি হবে।':'The amount must be more than zero.','বিলের তথ্য নেই।':'Bill information is missing.','বিলের পরিমাণ শূন্যের বেশি হবে।':'The bill amount must be more than zero.','প্রারম্ভিক মাসের আগের লেনদেন বা বিল যোগ করা যাবে না।':'The date is before the first account month.',
  'আমেনা খানম (9C)-এর মোবাইল নম্বর ব্যবহারকারী দিয়েছেন। বাকি ২৬ ফ্ল্যাটের নম্বর যোগ করতে হবে।':'The user provided Amena Khanom’s (9C) phone number. Phone numbers for the remaining 26 flats must be added.',
  'মে মাসের সমাপনী −৳১৪৪,০৩৪; জুনের ছবিতে প্রারম্ভিক −৳১৩৫,৫৩৪। ৳৮,৫০০ সমন্বয়ের সমর্থক লেনদেন নেই।':'May closes at −৳144,034, while the June image opens at −৳135,534. No supporting transaction was found for the ৳8,500 adjustment.',
  '8C: এপ্রিল ৳৩,০০০, মে ৳৬,০০০ বকেয়া। জুনে কোনো আদায় নেই কিন্তু বকেয়া ৳৬,০০০ দেখানো। গণনায় ৳৯,০০০।':'8C: Due was ৳3,000 in April and ৳6,000 in May. June shows no collection but reports ৳6,000 due; the calculation gives ৳9,000.',
  '9A: মে মাসের ৳৩,০০০ সার্ভিস বকেয়া জুনে নেই, আলাদা বকেয়া আদায়ের রসিদ নেই। মে মাসের ৳৫০০ গ্যারেজ ভাড়াও ছবির বকেয়ায় নেই।':'9A: The ৳3,000 May service due is absent in June, with no separate due-collection receipt. May’s ৳500 garage rent is also absent from the source due.',
  '2B-এর বকেয়া মাসে ৳৩,৫০০ বাড়ে। ৳৩,০০০ সার্ভিস + ৳৫০০ গ্যারেজ ধরে বিল তৈরি; প্রারম্ভিক বকেয়া ৳৪৬,৫০০ নির্ণীত। নিশ্চিত করুন।':'2B’s due increases by ৳3,500 each month. Bills use ৳3,000 service + ৳500 garage, and the opening due was calculated as ৳46,500. Please confirm.',
  '3B-এর ৳৩,৫০০ বকেয়া প্রতি মাসে একই; জানুয়ারির আগের বকেয়া হিসেবে রাখা হয়েছে।':'3B’s ৳3,500 due is unchanged each month and is recorded as a pre-January opening due.',
  '4C-এর মালিক জানুয়ারি–ফেব্রুয়ারিতে আশরাফুল হাসান মিথুন; মার্চে মোঃ মোতালেব এবং পরের ছবিতে মোঃ মোতালেব হোসেন। বর্তমান নাম জুনের ছবি থেকে।':'The owner of 4C is Ashraful Hasan Mithun in January–February, Md. Motaleb in March, and Md. Motaleb Hossain in later images. The current name comes from the June image.',
  'কয়েকটি প্রাপ্তির তারিখ হিসাবের মাসের পরে। মূল তারিখ ও হিসাবের মাস আলাদা রাখা হয়েছে; মাসিক হিসাব ছবির মাস অনুযায়ী।':'Several receipt dates fall after their account month. Original dates and account months are kept separately; monthly accounts follow the source-image month.',
  'বহিরাগত গ্যারেজ তালিকায় JAHID, MAHMUD ও ZAKIR একই মাসে একাধিকবার আছে। উৎসের প্রতিটি ক্রমিক আলাদা রসিদ; পরিচয় অনুমান করে এক করা হয়নি।':'JAHID, MAHMUD and ZAKIR appear multiple times in the outside-garage list for the same month. Each source line remains a separate receipt; identities were not guessed or merged.',
  'কিছু ব্যয়ের বর্ণনায় আগের মাস/অস্বাভাবিক তারিখ আছে; এপ্রিল সম্পাদকের তারিখ ১ মার্চ। মে ও জুনের কয়েকটি বর্ণনার বানান যাচাইযোগ্য। অঙ্কগুলো স্পষ্ট।':'Some expense descriptions contain a previous month or unusual date; April’s secretary entry is dated 1 March. Some May and June wording needs review. The amounts are clear.'
 };
 const rules=[
  [/ফ্ল্যাট মালিকদের তালিকা \((\d+)\)/g,'Flat Owner List ($1)'],[/([০-৯0-9]+)টি ফ্ল্যাটের মোবাইল নম্বর এখনো যোগ করা হয়নি। নাম ও ফ্ল্যাট নম্বর সংরক্ষিত আছে।/g,'Phone numbers are still missing for $1 flats. Names and flat numbers are saved.'],[/([০-৯0-9]+)টি ছবি/g,'$1 images'],[/([০-৯0-9]+)টি লেনদেন/g,'$1 transactions'],[/([০-৯0-9]+)টি বিল/g,'$1 bills']
 ];
 const read=()=>{try{return localStorage.getItem(KEY)==='bn'?'bn':'en';}catch{return 'en';}};
 let current=read();
 function t(value){let out=String(value??'');if(current!=='en')return out;for(const [pattern,replacement] of rules)out=out.replace(pattern,replacement);const keys=Object.keys(en).sort((a,b)=>b.length-a.length);for(const key of keys)out=out.split(key).join(en[key]);return out;}
 function setLanguage(value){current=value==='en'?'en':'bn';try{localStorage.setItem(KEY,current);}catch{}document.documentElement.lang=current;document.title=current==='en'?'Bijoy Tower — Service Charge & Accounts':'বিজয় টাওয়ার — সার্ভিস চার্জ ও হিসাব';return current;}
 function translate(container=document){if(current!=='en')return;const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(node.parentElement?.closest('script,style,[data-no-i18n]'))continue;node.nodeValue=t(node.nodeValue);}for(const el of container.querySelectorAll('[placeholder],[title],[aria-label]'))for(const attr of ['placeholder','title','aria-label'])if(el.hasAttribute(attr))el.setAttribute(attr,t(el.getAttribute(attr)));}
 root.I18n={get language(){return current;},setLanguage,t,translate};
})(globalThis);
